/********************************************************************
* tmp/modules/ModulesDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/modules/ModulesDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableModulesDict();
extern void G__cpp_setup_inheritanceModulesDict();
extern void G__cpp_setup_typetableModulesDict();
extern void G__cpp_setup_memvarModulesDict();
extern void G__cpp_setup_globalModulesDict();
extern void G__cpp_setup_memfuncModulesDict();
extern void G__cpp_setup_funcModulesDict();
extern void G__set_cpp_environmentModulesDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ModulesDictLN_TClass;
extern G__linked_taginfo G__ModulesDictLN_TBuffer;
extern G__linked_taginfo G__ModulesDictLN_TMemberInspector;
extern G__linked_taginfo G__ModulesDictLN_TObject;
extern G__linked_taginfo G__ModulesDictLN_TNamed;
extern G__linked_taginfo G__ModulesDictLN_TString;
extern G__linked_taginfo G__ModulesDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ModulesDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModulesDictLN_TObjArray;
extern G__linked_taginfo G__ModulesDictLN_TClonesArray;
extern G__linked_taginfo G__ModulesDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ModulesDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModulesDictLN_TIterator;
extern G__linked_taginfo G__ModulesDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ModulesDictLN_TTask;
extern G__linked_taginfo G__ModulesDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__ModulesDictLN_ExRootTask;
extern G__linked_taginfo G__ModulesDictLN_ExRootModule;
extern G__linked_taginfo G__ModulesDictLN_ExRootFilter;
extern G__linked_taginfo G__ModulesDictLN_MadGraphParticleClassifier;
extern G__linked_taginfo G__ModulesDictLN_MadGraphClassFilter;
extern G__linked_taginfo G__ModulesDictLN_MadGraphAnalysis;
extern G__linked_taginfo G__ModulesDictLN_MadGraphAnalysiscLcLParticleHistograms;
extern G__linked_taginfo G__ModulesDictLN_MadGraphAnalysiscLcLPairHistograms;
extern G__linked_taginfo G__ModulesDictLN_maplETStringcOMadGraphAnalysiscLcLParticleHistogramsmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOMadGraphAnalysiscLcLParticleHistogramsmUgRsPgRsPgR;
extern G__linked_taginfo G__ModulesDictLN_maplETStringcOMadGraphAnalysiscLcLPairHistogramsmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOMadGraphAnalysiscLcLPairHistogramsmUgRsPgRsPgR;
extern G__linked_taginfo G__ModulesDictLN_vectorlEconstsPKtJetcLcLKtLorentzVectormUcOallocatorlEconstsPKtJetcLcLKtLorentzVectormUgRsPgR;
extern G__linked_taginfo G__ModulesDictLN_reverse_iteratorlEvectorlEconstsPKtJetcLcLKtLorentzVectormUcOallocatorlEconstsPKtJetcLcLKtLorentzVectormUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModulesDictLN_vectorlEKtJetcLcLKtLorentzVectorcOallocatorlEKtJetcLcLKtLorentzVectorgRsPgR;
extern G__linked_taginfo G__ModulesDictLN_reverse_iteratorlEvectorlEKtJetcLcLKtLorentzVectorcOallocatorlEKtJetcLcLKtLorentzVectorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModulesDictLN_MadGraphKtJetFinder;
extern G__linked_taginfo G__ModulesDictLN_vectorlEPhysicsTowercOallocatorlEPhysicsTowergRsPgR;
extern G__linked_taginfo G__ModulesDictLN_reverse_iteratorlEvectorlEPhysicsTowercOallocatorlEPhysicsTowergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModulesDictLN_MidPointAlgorithm;
extern G__linked_taginfo G__ModulesDictLN_MadGraphConeJetFinder;
extern G__linked_taginfo G__ModulesDictLN_vectorlEClustercOallocatorlEClustergRsPgR;
extern G__linked_taginfo G__ModulesDictLN_reverse_iteratorlEvectorlEClustercOallocatorlEClustergRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
